# Generated by Django 5.1.3 on 2024-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='start_point',
        ),
        migrations.AddField(
            model_name='direction',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
