# Generated by Django 5.1.3 on 2024-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0003_remove_direction_start_point_direction_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='to_place',
        ),
        migrations.AddField(
            model_name='direction',
            name='from_district_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='direction',
            name='from_region_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='direction',
            name='to_district_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='direction',
            name='to_region_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
