# Generated by Django 5.1.3 on 2024-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0004_remove_direction_from_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
