# Generated by Django 5.1.3 on 2024-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0005_direction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='status',
        ),
    ]
