# Generated by Django 5.1.3 on 2024-12-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0007_direction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=255, unique='')),
                ('name', models.CharField(max_length=300, unique='')),
            ],
        ),
    ]
