# Generated by Django 5.1.3 on 2024-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0008_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
