# Generated by Django 5.1.3 on 2024-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0009_alter_topic_options_alter_topic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.BigIntegerField(),
        ),
    ]
