# Generated by Django 5.1.3 on 2024-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0010_alter_topic_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='region_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
